spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev #开发环境
    application:
        name: microservicecloud-config-deb
---
spring:
    profiles: test #测试环境
    appliction:
        name :microservicecloud-config-test